### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by DanielIbaseta** [pfalcon/picoweb#38]
¿Is it possible to add basic security check to this webserver? I mean, like a popup when trying to access a certain URL.

**Comment by lingster** [comment]
A typical Web framework would provide a login/authentication mechanism. So if you are implementing a rest api via pico Web, then create a login endpoint which takes a username and password and returns a token. Your password protected url would then check that the token is valid and included in the request header. For generating a token there are various ways of doing this, including JWT or even just a random hash with a time limit validity that would have to be stored on the server. 
I think if you started adding things like this then picoweb would start to get bloated.... I suppose this kind of functionality could be added in as a plugin to picoweb?

One other additional feature to add is an ssl implementation, otherwise your password could be sniffed as http sends data in clear text.

**Comment by pfalcon** [comment]
> Is it possible to add basic security check to this webserver?

Picoweb is a just a generic HTTP server. Everything which is possible with HTTP, possible with picoweb.

Actual implementation of various features is up to the users - feel free to develop plugins like you develop for Flask, or whatever.

Anyway, I added an example of HTTP Basic authentication: https://github.com/pfalcon/picoweb/blob/master/examples/example_basic_auth.py
