### ISSUE TITLE
Headers are stored unaltered, making them case sensitive. HTTP spec says they should be insensitive

### ISSUE THREAD

**Issue by etjones** [pfalcon/picoweb#63]
The HTTP/1.1 & HTTP/2 standard,  according to [RFC 2616](http://www.ietf.org/rfc/rfc2616.txt) says:

4.2: 
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

Picoweb parses headers and stores them unaltered, meaning if a client passes `Content-Type:application/json` in a header, `req.headers.get('content-type')` will return `None`. 

Since different clients pass differently capitalized header keys, (and I guess that's OK, according to the standard) we can either check for all cases of headers ( `if b'content-type in [k.lower() for k in req.header.keys()]:`)  or I would propose storing header keys in a single 
case.  The change would go in `WebApp.parse_headers()`:  the original `headers[k] = v.strip()` would become, say, `headers[k.lower()] = v.strip()`

**Comment by pfalcon** [comment]
Picoweb aims to be a minimalist, real-world practical solution to make writing simple webapps easy, and more complex webapps possible (by extending picoweb's existing functionality), not a thing which tries to wear badges like "100% HTTP standard support". So, as long as it works with well-known, popular clients, fringe cases are left out for special handling by users who actually need it.

> Since different clients pass differently capitalized header keys

I never saw that among well-known, popular clients. All I know use the header names exactly as written in the standard, not something else. If you're aware of well-known, popular clients doing otherwise, please ask them why they're doing so.

> The change would go in WebApp.parse_headers()

Users who have additional needs while processing headers, or other processing done by picoweb, would subclass WebApp and override methods as needed. This is mentioned in https://github.com/pfalcon/picoweb#reporting-issues , p.4, and also discussed in detail in https://github.com/pfalcon/picoweb/issues/61.
